services:
  - type: web
    name: mechanic-shop-api
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9