services:
  - type: web
    name: mechanic-shop-api
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: Postgres_DATABASE_URI
          property: connectionString